version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile  # Assuming this is your Dockerfile for the ASP.NET Core app
    ports:
      - "5099:8080"  # Map container's port 5099 to host port 5099
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=CustomFormsDB;Username=postgres;Password=postgres"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - aspnetcoreapp-network
      

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CustomFormsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL port if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    volumes:
      - ./Migrations/V1__Initialize_Database.sql:/docker-entrypoint-initdb.d/V1__Initialize_Database.sql 
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

